### ISSUE TITLE
cannot import library

### ISSUE THREAD

**Issue by socar-chef** [vincentsong/react-native-datepicker-component-android#2]
i'm using react 16.0.0
react-native 0.49.5

it occurs error "undefined is not an object" after just import library.

specific error messages below,

undefined is not an object (evaluating '_react3.default.RpopTypes.func')

<unknown>
index.js:39:28

loadModuleImplementation
require.js:178.12
...

and after  Enable Js debug remotely,

It shows another error title,

Cannot read property 'func' of undefined

and below errors same.

**Comment by socar-chef** [comment]
alright, I solved problem.

Using React.PropTypes, in your `index.js`, which removed in react >= 16.0.0

try using `import PropTypes from 'prop-types` 

i've solve with make new component from your native RCTDatePickerComponent.

and thanks again for solve spinner issue.

**Comment by vincentsong** [comment]
Thanks for your contribution
